# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload a new version to alpha track of the Play Store"
  lane :alpha do
    #gradle(task: "clean assembleRelease")
    #crashlytics
    #gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      # Skip upload because otherwise Google Play needs to verify the 'new' files again.
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end
end
