name: Android release
on: workflow_dispatch
jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.x'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: green_walking
    - name: Build appbundle
      run: |
        flutter build appbundle \
          --dart-define MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }} \
          --dart-define FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          --dart-define FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
          --dart-define FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
          --dart-define FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
      working-directory: green_walking
