name: Flutter
on: push
jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'
        channel: 'stable'
    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Install dependencies
      run: flutter pub get
      working-directory: green_walking
    - name: Check format
      run: make format-check
      working-directory: green_walking
    - name: Run linter
      run: make lint
      working-directory: green_walking
    - name: Run tests
      run: make test
      working-directory: green_walking
