name: Flutter check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' 
    - run: flutter pub get
      working-directory: apps/green_walking
    - run: dart format --set-exit-if-changed .
      working-directory: apps/green_walking
    - run: flutter analyze .
      working-directory: apps/green_walking
    - run: flutter test
      working-directory: apps/green_walking
