name: Flutter
on: push
jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.x'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: green_walking
    # FIXME: Disabled because of generated l10n files.
    #- name: Check format
    #  run: make format-check
    #  working-directory: green_walking
    - name: Run linter
      run: make lint
      working-directory: green_walking
    - name: Run tests
      run: make test
      working-directory: green_walking
