name: Flutter
on: push
jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: green_walking
    - name: Check format
      run: find . -name '*.dart' -not -name 'messages_*.dart' -exec flutter format --set-exit-if-changed {} \;
      working-directory: green_walking
    - name: Run linter
      run: flutter analyze .
      working-directory: green_walking
    - name: Run tests
      run: flutter test .
      working-directory: green_walking
