name: Flutter check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta' 
    - name: Install dependencies
      run: flutter pub get
      working-directory: apps/green_walking
    #- name: Check format
    #  run: dart format --set-exit-if-changed .
    #  working-directory: apps/green_walking
    - name: Run linter
      run: flutter analyze .
      working-directory: apps/green_walking
    - name: Run tests
      run: flutter test .
      working-directory: apps/green_walking
